version: '3.5'

networks:
    localdev:
        name: localdev

volumes:
    sqlserverdata:

services:
    app:
        build: ./
        restart: always
        ports:
            - '5000:5000'
        depends_on:
            - db
        networks:
            - localdev
        volumes:
            - .:/app

    db:
        image: microsoft/mssql-server-linux:2017-latest
        container_name: db
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Nick1234
            - MSSQL_TCP_PORT=1433
        ports:
            - '1400:1433'
        networks:
            - localdev
        volumes:
            - sqlserverdata:/var/opt/mssql/data
